### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by dittos** [dittos/graphql-py#1]
## Implemetation
- [x] lexer
- [x] parser
- [x] ast printer
- [x] ast visitor
- [x] schema type
- [x] base types (scalar, object, interface, union, enum)
- [x] wrapper types (non-null, list)
- [x] scalar types (int, float, string, id)
- [ ] directives
- [x] introspection
- [x] validators
- [ ] type printer

### `src/__tests__`
- [ ] `starWarsData.js`
- [ ] `starWarsSchema.js`
- [ ] `starWarsIntrospectionTests.js`
- [ ] `starWarsValidationTests.js`
- [ ] `starWarsQueryTests.js`

### `src/executor/__tests__`
- [ ] `directives.js`
- [x] `executor.js`
- [x] `executor_schema.js`
- [x] `input_object.js`
- [x] `lists.js`
- [x] `mutations.js`
- [x] `nonnull.js`
- [x] `union-interface.js`
- [x] `variables.js`

### `src/language/__tests__`
- [x] `lexer.js`
- [x] `parser.js`
- [x] `printer.js`
- [x] `visitor.js`

### `src/type/__tests__`
- [x] `coercion.js`
- [x] `definition.js`
- [x] `introspection.js`
- [ ] `validator.js`

### `src/validator/__tests__`
...

**Comment by sairion** [comment]
:+1:

**Comment by syrusakbary** [comment]
:+1:

**Comment by su27** [comment]
:+1:

**Comment by dittos** [comment]
Will track as separate issues.
