### ISSUE TITLE
I'd like to help

### ISSUE THREAD

**Issue by jhgg** [dittos/graphql-py#10]
Following the resolution of #9, I've gotten approval from work to help out on this project (as it's something we're looking on using internally) and upstream all our changes.

Question is: what do you need help on & what can I do?

Reply, or shoot me an e-mail: me@jh.gg so we can discuss this more, and see where I can aide in getting this to be complete, following #1 and #6. 

Thanks!

**Comment by rawls238** [comment]
I'm also up for helping with this project, let me know what I can do to help

**Comment by sairion** [comment]
One of the thing I know is: https://github.com/dittos/graphql-py/issues/6 which is the list of the validation rules that needed to be ported from graphql-js.

**Comment by dittos** [comment]
For now, it would be great if you help implementing validation rules (see #6), as @sairion said. Please leave a comment in that issue before start working, to prevent duplicate work.

Thanks!

**Comment by Mec-iS** [comment]
Hi,
I am making research on the same arguments as well (Python and graphQL), trying to create a Falcon web server that can serve data from different REST endpoints, replying a graphQL query . 
I prepared a quite [properties-rich test API](https://github.com/Mec-iS/mild-QL), with a prototype running [here](http://mild-ql.appspot.com/). You can find Swagger documentation in the [apidoc directory](https://github.com/Mec-iS/mild-QL/tree/master/apidoc).

Cheers!

PS. forward to @ariutta

**Comment by woodb** [comment]
I suggest that we close this one and direct folks who find this thread towards #6
