### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by dittos** [dittos/graphql-py#14]
PyPI package name `graphql-py` is already taken by https://github.com/ivelum/graphql-py

PyPI package name `graphql`, `pygraphql`, `graphql-python` are already taken.

Possible alternative name?

**Comment by woodb** [comment]
How about `libgraphql`?

**Comment by ivome** [comment]
`python-graphql` and `py-graphql` seem to be free...

**Comment by dittos** [comment]
Some candidates:

* Names that resembles graphql
  * grapyql / graphyql / grapyhql: confusing, bad for SEO
  * (py)gql: didn't see GraphQL abbriviated to GQL
  * gqlalchemy / graphqlalchemy: it sounds like GraphQL integration for SQLAlchemy
  * python-graphql / py-graphql / graphql2 / ...: I don't want to add any more confusion to the PyPI registry
* Completely different names (like [Sangria](http://sangria-graphql.org/))
  * baton: as in Relay

**Comment by pm5** [comment]
Some examples of GraphQL as GQL: [koa-gql](https://www.npmjs.com/package/koa-gql), [a Ruby implementation](https://rubygems.org/gems/gql).

**Comment by woodb** [comment]
I actually really like `baton`, that's clever :)

**Comment by sairion** [comment]
I like `baton` as well :+1:

**Comment by jhgg** [comment]
Only issue with `baton` is that it makes it hard to discover this project. I think gql/graphql should be somewhere in the name.

**Comment by dittos** [comment]
I decided to use `graphqllib`. Reserved PyPI package name: https://pypi.python.org/pypi/graphqllib Will update project info soon.

**Comment by woodb** [comment]
:+1:
