### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by woodb** [dittos/graphql-py#16]
It looks like we could get Python 2.6 support by just changing the way that formatted strings are defined to include the argument number.

`tox -epy26` results in the following output:
https://gist.github.com/woodb/05795c29334d17d06f2a.js

I'd be willing to take this on, but it does require updating the following files, so I wouldn't want the PR to get too stale.
```
graphql/core/execution/values.py
graphql/core/language/error.py
graphql/core/language/lexer.py
graphql/core/language/parser.py
graphql/core/language/printer.py
graphql/core/validation/rules.py
```

**Comment by rawls238** [comment]
seems like something we should do after https://github.com/dittos/graphql-py/issues/6 is finished off

**Comment by woodb** [comment]
Agreed @rawls238

**Comment by woodb** [comment]
After looking at what it would take to support Python 2.6, I'm thinking that it's not really important. Esp. since we're dealing w/ a hip new tech, I don't see anyone using it still being on Python 2.6 that would want to use it (while I would argue that #17 was necessary for this same reason).

Closing this one out, but if someone has a compelling reason to want to support 2.6, we can reopen it.
