### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by woodb** [dittos/graphql-py#17]
We should probably want to support Python 3, since we currently have no dependencies that keep us from supporting it and it moves things forward a little more...

**Comment by woodb** [comment]
Like #16, I'd be willing to take this one on also but again it requires touching kind of a lot of files and a stale PR would be a bummer :100:

**Comment by woodb** [comment]
Sickkkkk

**Comment by mpaolini** [comment]
why not using six?
