### ISSUE TITLE
Refactor coerce to parse/serialize in scalar types

### ISSUE THREAD

**Issue by dittos** [dittos/graphql-py#32]
https://github.com/graphql/graphql-js/blob/f9a287754898faf850101045f7d63000ea1b2159/src/type/definition.js#L242-L248

**Comment by jhgg** [comment]
Do you mean to say refactor coerce to parse?

**Comment by dittos** [comment]
@jhgg Yes. See also https://github.com/graphql/graphql-js/commit/90d0b0d71744cc59ec25d865547ccc74a7a85e79

I'm working on it now.
